### ISSUE TITLE
FASTA only allowed from ensembl

### ISSUE THREAD

**Issue by NikdAK** [bcgsc/Terminitor#1]
Hi,
I noticed that only FASTAs from ensembl are allowed, because you expect a specific header structure (>1 dna:chromosome chromosome:GRCm38:1:1:195471971:1 REF).
Headers from like gencode (>1 1) will cause a break in extract_from_sequences.py at length = int(info[2].split(':')[4]).

Maybe you should address this in the tutorial, since it can cause some confusion.
Thank you!

**Comment by cheny19** [comment]
Hi @NikdAK ,

Thanks for pointing this out! I'll update my code so it will cope with both cases. Hopefully it will be done by tomorrow.

Chen

**Comment by cheny19** [comment]
Hi @NikdAK,

I did some tests and have never encountered a case where the candidate sequence is too close to the end of a chromosome. So I simply removed that check. Now it should be compatible with any reference genome in FASTA format.

Cheers,
Chen
